 
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
 

 
public class MAINFORM extends javax.swing.JFrame {

    /** Creates new form MAINFORM */
    public MAINFORM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1_mod1 = new javax.swing.JButton();
        jButton2_mod2 = new javax.swing.JButton();
        jButton3_mod3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_Mod1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2_mod2 = new javax.swing.JTextArea();
        jTextField1_K_value = new javax.swing.JTextField();
        jLabel_K_Value = new javax.swing.JLabel();
        jLabel1_N_Value = new javax.swing.JLabel();
        jTextField2_N_Value = new javax.swing.JTextField();
        jTextField1_d = new javax.swing.JTextField();
        jLabel1_d = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_c1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1_mod1.setText("Module 2:Shamir Secret Share Generation");
        jButton1_mod1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_mod1MouseClicked(evt);
            }
        });
        jButton1_mod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_mod1ActionPerformed(evt);
            }
        });

        jButton2_mod2.setText("Module 3:Shamir Secrete Recovery");
        jButton2_mod2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_mod2MouseClicked(evt);
            }
        });
        jButton2_mod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_mod2ActionPerformed(evt);
            }
        });

        jButton3_mod3.setText("Module 4:Generation of a Stego-Image (png)");
        jButton3_mod3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3_mod3MouseClicked(evt);
            }
        });
        jButton3_mod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_mod3ActionPerformed(evt);
            }
        });

        jButton4.setText("Module 5:Authentication of stego-image(png)");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1_Mod1.setColumns(20);
        jTextArea1_Mod1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_Mod1);

        jTextArea2_mod2.setColumns(20);
        jTextArea2_mod2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2_mod2);

        jTextField1_K_value.setEditable(false);
        jTextField1_K_value.setText("2");

        jLabel_K_Value.setText("K value");

        jLabel1_N_Value.setText("N value");

        jTextField2_N_Value.setEditable(false);
        jTextField2_N_Value.setText("6");

        jTextField1_d.setText("0-15");
        jTextField1_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_dActionPerformed(evt);
            }
        });

        jLabel1_d.setText("d secrete value");

        jLabel1.setText("c1");

        jTextField1_c1.setText("0-15");

        jButton2.setText("Module 6:Generation of a Stego-Image (jpg)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Module 7:Authentication of stego-image(jpg)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jButton1_mod1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addComponent(jButton2_mod2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3_mod3, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jTextField1_K_value, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2_N_Value, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField1_d, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_K_Value)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1_N_Value)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1_d)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_mod1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2_mod2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3_mod3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_K_value, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_N_Value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_K_Value)
                    .addComponent(jLabel1_N_Value)
                    .addComponent(jLabel1_d)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(95, 95, 95))
        );

        jButton1.setText("Module1: Noise Removal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("PSNR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_mod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_mod2ActionPerformed
        // TODO add your handling code here:
         //System.out.println("Enter "+jTextField1_K_value.getText()+"shares");
    }//GEN-LAST:event_jButton2_mod2ActionPerformed

    private void jButton1_mod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_mod1ActionPerformed
        // TODO add your handling code here:
        jTextArea1_Mod1.setText("K= "+jTextField1_K_value.getText()+"  N= "+jTextField2_N_Value.getText()+" Secrete d= "+jTextField1_d.getText());
       //jTextArea1_Mod1.setText("K= "+"\t"+jTextField1_K_value.getText());
        //jTextArea1_Mod1.setText("N= "+"\t"+jTextField2_N_Value.getText());
    }//GEN-LAST:event_jButton1_mod1ActionPerformed

    private void jButton1_mod1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_mod1MouseClicked
        // TODO add your handling code here:
            shamir gs=new shamir();
            BigInteger d=new BigInteger(jTextField1_d.getText());
            BigInteger c1=new BigInteger(jTextField1_c1.getText());
            
            
             
             
            BigInteger s[] =new BigInteger[2];
         
            s[0]=d;
            s[1]=c1;
            shamirKey[] generateKeys = null;
        try {
            generateKeys = gs.generateKeys(6,2, 8,s);
        } catch (shamirException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println(d+"  "+c1);
            System.out.println(generateKeys[0].getP());
            for (int i=0;i<6;i++)
            System.out.println(generateKeys[i].getX()+":"+generateKeys[i].getF());
            
            
            
            
            
   jTextArea1_Mod1.setText("K= "+jTextField1_K_value.getText()
           +"  N= "+jTextField2_N_Value.getText()+
           " Secrete d= "+jTextField1_d.getText()+
           "\nF(x)="+"("+jTextField1_d.getText()+
           "+"+jTextField1_c1.getText()+
           "*x)mod17"+"\n\n6 shares :\n "+
           "\nF(1)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*1))%17 +
           "\nF(2)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*2))%17 +
           "\nF(3)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*3))%17 +
           "\nF(4)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*4))%17 +
           "\nF(5)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*5))%17 +
           "\nF(6)="+((Integer.parseInt(jTextField1_d.getText())+Integer.parseInt(jTextField1_c1.getText())*6))%17 +
           "");
   //jTextArea1_Mod1.setText("N= "+"\t"+jTextField2_N_Value.getText());
    }//GEN-LAST:event_jButton1_mod1MouseClicked

    private void jButton2_mod2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_mod2MouseClicked
        // TODO add your handling code here:
         //jTextArea2_mod2.getSelectedText();
        
       
         System.out.println("Enter "+jTextField1_K_value.getText()+" shares\n");
         BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
         String userName[]=new String[2];
         String split[][] =new String[2][2];
         for(int i=0;i<Integer.parseInt(jTextField1_K_value.getText());i++)
         {System.out.println("Enter "+(i+1)+"th share separated by ;"+"\n");
         try {
             userName[i] = br.readLine();
             String[] sp1= userName[i].split(";");
             split[i][0]=sp1[0];
             split[i][1]=sp1[1];
             System.out.println("x= "+split[i][0]+"\t"+"F(x)="+split[i][1]);
         } catch (IOException ioe) {
             System.out.println("IO error trying to read data!");//System.exit(1);
         } 
         }
                   
     shamirKey[] sk=new shamirKey[2] ;
            //sk[0].setP();
     byte[] val=new byte[1];
     val[0]=17;
     BigInteger bi= new BigInteger(val);
    sk[0]=new shamirKey();
    sk[1]=new shamirKey();
               sk[0].setP(bi ); 
               sk[0].setX( new BigInteger(split[0][0]));
               sk[0].setF( new BigInteger(split[0][1]));
               sk[1].setP(BigInteger.valueOf(17)); 
               sk[1].setX( new BigInteger(split[1][0]));
               sk[1].setF( new BigInteger(split[1][1]));
                
         
        shamir rs=new shamir();
           byte[] calculateLagrange = shamir.calculateLagrange(sk);
            System.out.println(calculateLagrange.length);
            System.out.println("Secrete Recovered="+calculateLagrange[0]);
        
         
            
             jTextArea2_mod2.setText( 
           
          
           "\n\n2 shares used :\n "+
           "\nF("+ sk[0].getX()+")="+sk[0].getF()+
           "\nF("+ sk[1].getX()+")="+sk[1].getF()+
           "\n\n Secrete Recovered= "+jTextField1_d.getText()+
            
           "");
         
    }//GEN-LAST:event_jButton2_mod2MouseClicked

    private void jTextField1_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_dActionPerformed

    private void jButton3_mod3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3_mod3MouseClicked
        // TODO add your handling code here:
         
         ALGO_3 a3=new  ALGO_3();
        try {
            a3.MAIN(" ");
        } catch (IOException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
          
       

    }//GEN-LAST:event_jButton3_mod3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ALG4_GRAY alg4 =new ALG4_GRAY();
        alg4.MAIN("");
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
     ALGO_4 a4=new  ALGO_4();
        try {
            a4.MAIN(" ");
        } catch (IOException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
ALG5_GRAY alg5=new ALG5_GRAY();
        try {
            alg5.MAIN("");
// TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // medianFiltering  mf=new medianFiltering();
        //mf.start();
   MedianFilter_1 mm=new MedianFilter_1();
        try {
            mm.MAIN("");
        } catch (Throwable ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3_mod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_mod3ActionPerformed
        // TODO add your handling code here:
         ALG3_GRAY alg3= new ALG3_GRAY ();
        try {
            alg3.MAIN("");
        } catch (IOException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3_mod3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
ALG6_GRAY nn=new ALG6_GRAY();
nn.MAIN("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            PSNR.MAIN("");
        } catch (IOException ex) {
            Logger.getLogger(MAINFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new MAINFORM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_mod1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2_mod2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton3_mod3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_N_Value;
    private javax.swing.JLabel jLabel1_d;
    private javax.swing.JLabel jLabel_K_Value;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1_Mod1;
    private javax.swing.JTextArea jTextArea2_mod2;
    private javax.swing.JTextField jTextField1_K_value;
    private javax.swing.JTextField jTextField1_c1;
    private javax.swing.JTextField jTextField1_d;
    private javax.swing.JTextField jTextField2_N_Value;
    // End of variables declaration//GEN-END:variables

}
